### ISSUE TITLE
Predix Components not working after updating to new version Google Chrome 80

### ISSUE THREAD

**Issue by snacky996** [PredixDev/px-app-nav#113]
*After updated Google Chrome browser from 79 to 80, Most of predix components stop working in live project and creating a multiple problems on production server.

*Chrome dropped support for HTML imports which are used by PX components. See my reply in this thread about the webcomponents polyfill version workaround.

*I have seen information on this topic that the Predix UI dev team is fixing bugs; please let me know the completion time or any workaround the method.

https://forum.predix.io/questions/34166/predix-components-not-working-after-updating-to-ne.html

Thank you for your support.

**Comment by snacky996** [comment]
@evanjd @e-kag @leebickmtu @mdwragg  @randyaskin  @davidrleonard

**Comment by leebickmtu** [comment]
This probobly has to due with Web Components v0 APIs being [removed in Chrome 80](https://developers.google.com/web/updates/2019/07/web-components-time-to-upgrade).

I haven't verified this, but from what I'm seeing if you are using Polymer v1 or v2 you just need to make sure you are properly [loading the Web Components polyfills](https://www.polymer-project.org/blog/2018-10-02-webcomponents-v0-deprecations).

**Comment by snacky996** [comment]
@leebickmtu :  I see px-app-nav has branch "polymer-upgrade" - upgrade from polymer 2 to 3 via polymer CLI. But don't know the master branch has been merged and can work on v3 polymer?
