### ISSUE TITLE
Custom KeyframeEffect Uncaught Error:

### ISSUE THREAD

**Issue by jonniespratley** [PredixDev/px-app-nav#12]
- The version of `web-animations.js` in the demo is `0.7.21`
- The version in `bower.json` is `~2.0.0`
- The error comes when using version greater than 1.0.0.

https://cdnjs.com/libraries/web-animations does not even list this version. 

Need to fix component.

**Comment by jonniespratley** [comment]
Here is a Fiddle example. https://jsfiddle.net/JonnieSpratley/1zjbw1uv/13/

**Comment by dmcalpin** [comment]
i have a PR open that fixes this - https://github.com/PredixDev/px-app-nav/pull/14
