### ISSUE TITLE
px-app-nav nav-expanded not inline with the code

### ISSUE THREAD

**Issue by clementchi** [PredixDev/px-app-nav#15]
@ek:

in px-app-nav-sketch.scss line 61 :host[nav-expanded], :host[nav-contracting] {

But in the px-app-nav 

```
  navExpanded: {
    value: "true",
    type: String,
    reflectToAttribute: true
  },
```

navExpaned property will set the navExpanded value = true in the attribute so that the style will not be picked up.

**Comment by murone** [comment]
This is a function of how polymer handles properties and attributes. 
https://www.polymer-project.org/1.0/docs/devguide/properties#property-name-mapping
