### ISSUE TITLE
px-app-nav won't contract when screen width is less than 63.9rem

### ISSUE THREAD

**Issue by kdinluks** [PredixDev/px-app-nav#18]
The expected behavior is that when the screen width is less than 63.9rem the px-app-nav should retract itself, but it's not happening.
The problem is that you're using a computed property to handle the contraction / expansion, but with a computed property you cannot change it's value directly.
The function _checkMediaMatches is working fine until line 222 and 228 when it tries to set the computed property value, which never happens, and therefore the nav never contracts.
222: `this._navExpanded = false;`
228: `this._navExpanded = true;`

I have changed it to set the external property navExpanded instead of the internal _navExpanded and then I changed the function _checkNavExpandedState to use the external property instead of the internal and that seems to fix the issue.

**Comment by kdinluks** [comment]
@ek @clementchi could any of you take a look at this?

**Comment by ek** [comment]
Hi @kdinluks , I am looking into it now. Please standby for a response today.

**Comment by kdinluks** [comment]
Thanks @ek, I will be looking out for the fix. I've send a pull request with a fix if you want to take a look at it as well.

**Comment by kdinluks** [comment]
You can also test it here using this codepen: http://codepen.io/kdinluks/pen/NrRGNm
Just resize the windows to less than 1022px and you will see that the menu contracts and expands right away.

**Comment by ek** [comment]
Thanks @kdinluks 

The issue should be resolved in v1.7.0 - please upgrade in your bower.json and install again to get the new code.

Please confirm and I will close this issue 💃

**Comment by kdinluks** [comment]
@ek it seems to be solved. Thanks.
