### ISSUE TITLE
Tooltip still displayed when nav expanded

### ISSUE THREAD

**Issue by randyaskin** [PredixDev/px-app-nav#20]
@clementchi - the tooltip is still being displayed when the navigation is expanded. Maybe the hidden behavior set in px-app-nav is getting overwritten by the hover event listeners in px-tooltip?

**Comment by clementchi** [comment]
Thanks @randyaskin I will look into it.

**Comment by clementchi** [comment]
@randyaskin, It is fixed in version 1.7.1.
