### ISSUE TITLE
depserve crashes when trying to serve on localhost

### ISSUE THREAD

**Issue by murone** [PredixDev/px-app-nav#22]
See error below. Changing 0.0.0.0 manually in npm_modules/grunt-dep-serve/tasks/grunt-dep-serve.js to "localhost" in all instances fixes the issue.

## Expected behavior and actual behavior:
grunt devmode or grunt depserve should serve me the page for testing (local dev, so trying to serve index.html). 

## Steps to reproduce the problem:
clone, npm install, bower install, grunt devmode 

## Environment (_component version number, Browser (including version), operating system, hardware, etc_):
commit  f7d3c19 , chrome, Windows 10

## Code examples help us better understand the issue

error in terminal: 

```
210071205 (master *) px-app-nav-bf $ grunt devmode --force
(node:7364) DeprecationWarning: process.EventEmitter is deprecated. Use require('events') instead.
Running "concurrent:devmode" (concurrent) task
    Running "watch" task
    Waiting...
    Running "depserve" task
    (node:12604) DeprecationWarning: process.EventEmitter is deprecated. Use require('events') instead.
    Local http server listening at http://localhost:8080/ with dependencies proxied from /bower_components
    ctrl+c to exit
    (node:8516) DeprecationWarning: process.EventEmitter is deprecated. Use require('events') instead.
    Fatal error: connect EADDRNOTAVAIL 0.0.0.0:8080
Warning: (node:12604) DeprecationWarning: process.EventEmitter is deprecated. Use require('events') instead. Used --force, continuing.

Done, but with warnings.
```

**Comment by mdwragg** [comment]
Fixed by a2176f2184e35ed1e00f895efab6dc32fe721d08 - we're moving to `gulp`.

Depserve has been replaced by `gulp serve`. 

Docs haven't been updated yet to reflect this - it is work in progress... ;)

Thanks for the defect!
