### ISSUE TITLE
Adding/applying custom classes to nav items

### ISSUE THREAD

**Issue by infinityplusone** [PredixDev/px-app-nav#28]
# Submit an Issue
## Expected behavior and actual behavior:

When adding a `class` property to the JSON feeding the nav, I would expect that value to carry through to the items. It is not. 
## Steps to reproduce the problem:

Add a value for `class` on any nav item or subitem. That class isn't carried through.
## Location in code this is happening:

https://github.com/PredixDev/px-app-nav/blob/master/px-app-nav.html#L381
https://github.com/PredixDev/px-app-nav/blob/master/px-app-nav.html#L385

Perhaps I'm misunderstanding how this is supposed to work, but I would've thought that those lines should be toggling _just_ the `selected` class. Or, if this is meant to be more general, that the JSON-defined value for `class` or `classList` would be stored elsewhere and appended here.

If I _am_ misunderstanding, how/where would I add my own classes to nav elements?

Thanks!

**Comment by infinityplusone** [comment]
Note: I realize that those lines are in the `markSelected` method, but it looks like that method (or maybe another?) is overriding the values for `class`, thus making it impossible to add a sticky value anywhere.

**Comment by davidrleonard** [comment]
This issue is for an outdated version of px-app-nav (v1.x). The new version has a revamped API and style variables available that allow you to theme selected items. Please take a look at the docs for more info: https://www.predix-ui.com/#/elements/px-app-nav
