### ISSUE TITLE
Latest Version (1.9.18) Background Missing

### ISSUE THREAD

**Issue by AMcManigal** [PredixDev/px-app-nav#30]
# Submit an Issue

Hi,

Thanks for helping us improve the Predix UI platform by submitting an issue.

Before you begin, please check the list of existing issues to avoid submitting a duplicate issue.

To help us solve this issue as fast as possible, please fill out the following sections:

## Expected behavior and actual behavior:

When I try to use the latest version (1.9.18) then the components background is missing. Using an earlier version (1.9.1) displays the expected result.

## Steps to reproduce the problem:

Use the different versions.

## Screenshots (_optional, but very helpful_):

![screen shot 2016-12-05 at 11 56 50 am](https://cloud.githubusercontent.com/assets/1545624/20894203/846698d8-bae2-11e6-8868-c008797510dd.png)
![screen shot 2016-12-05 at 11 54 52 am](https://cloud.githubusercontent.com/assets/1545624/20894207/87232898-bae2-11e6-8183-12e0da663fec.png)

**Comment by mdwragg** [comment]
Hi,

Thanks for your issue - are you loading px-theme anywhere on your page? Something like this:

  <link rel="import" href="../px-theme/px-theme-styles.html">
  <style include="px-theme-styles" is="custom-style"></style>

**Comment by murone** [comment]
Same issue here. Looks like we are using px-theme-styles.html as an import (<link rel="import:....../)

Wasn't happening until a recent update of px-app-nav tho. has something changed that we need to account for?

**Comment by murone** [comment]
Also FWIW commenting out that import doesn't seem to fix it.

**Comment by mdwragg** [comment]
Hi, we can't recreate this locally, can you give us a codepen/fiddle that shows the issue please? Thanks!

**Comment by krenabeth** [comment]
Here's an [example of the issue](https://github.build.ge.com/212591685/nav-test)

**Comment by murone** [comment]
@mdwragg we had that test repo from @krenabeth testing to see if it had to do with our specific implementation. we can try to recreate in codepen/fiddle if you need but that repo should be low enough complexity for you to test.

**Comment by randyaskin** [comment]
In either index.html or nav-test-app.html, you need the following two lines:

```
<link rel="import" href="/bower_components/px-theme/px-theme-styles.html">
<style include="px-theme-styles" is="custom-style"></style>
```

**Comment by murone** [comment]
That looks to have fixed it...was that style inclusion and import formerly in app-nav? Or were you just using CSS before and switched to style modules?

**Comment by murone** [comment]
OHHHH I found it...you kept px-theme around as a fallback until right before the 2.0 release, so we were riding that wave, and since it was just a style tag instead of a full dom-module, we didn't need the style inclusion there. Makes sense now. Thanks! Not a bug...just breaking change between major versions, which is to be expected.
