### ISSUE TITLE
px-app-nav modifies the navItems object

### ISSUE THREAD

**Issue by dsiefert** [PredixDev/px-app-nav#31]
I ran into some unexpected issues in my application because I was populating px-app-nav from an object which I reference elsewhere; this caused some unanticipated effects elsewhere in the application when px-app-nav modified the object to store state. Most examples I've found populate the nav with an array literal, so my use case may be somewhat unusual.

I ended up fixing the problem by using lodash to deep clone my array object and binding the clone.

Note that this occurred despite the fact that I did not use a two-way data binding. That's not too surprising, given that it is technically modifying the referenced object, not the reference, but I still find this somewhat counterintuitive. If state is going to be stored by modifying the navItems object, I would expect the element to clone the object and modify the new object instead.

## Expected behavior

Nav element avoids modifying navItems object.

## Actual behavior

Nav element stores state by modifying navItems object, which can cause unexpected results if other elements have references to the object.

## Steps to reproduce

Bind an object rather than using an array literal to supply nav items; watch the object from somewhere else where it can be examined (e.g. set it as a property of some other element, and inspect the element from the browser console). Note that the object is modified.

## Environment

All.

## Proposed fix

In the ready and _observeChanged callbacks, rather than directly modifying the object, clone it and save the clone to a private _navItems property, and store px-app-nav's state in this object.

If others agree that this is a legitimate issue and a good fix, I'm happy to submit a pull request to do it.

**Comment by murone** [comment]
Damon is part of a Pod I lead at the DTH where we're leveraging this element. As he stated in his proposed fix, we're prepared to take on the development ourselves and contribute it back, but didn't want to do the work until we confirm that the PX- team is open to the change. We wanted to run it by you all before putting the work in as we may try to find another way around it if the pull request won't be accepted.

**Comment by gedesigntech** [comment]
Hello @dsiefert @murone please feel free to contribute a solution back; please provide sufficient test coverage with it.  Thank you

**Comment by mdwragg** [comment]
Would it not be as simple as switching `notify: true` to `false` on navItems? Might be massively oversimplifying it there :)

That said, this would be API breaking so would require a major bump. I can't with any certainty say that people don't rely on this feature of notifying changes back...

You should always be able to rationalise a good web components' state by its properties too... Moving to what you propose would mean that would no longer be possible.

Which is a long way of me saying, I'm not entirely sure it is a good idea but don't have much to support this hunch ;-)

**Comment by davidrleonard** [comment]
This issue is for an outdated version of px-app-nav (v1.x). The new version has a revamped API and explicitly avoids mutating the `items` passed in by the developer.
