### ISSUE TITLE
how to add sub menu to sub menu in px-app-nav

### ISSUE THREAD

**Issue by pd98056** [PredixDev/px-app-nav#33]
# Submit an Issue

Hi,

Thanks for helping us improve the Predix UI platform by submitting an issue.

Before you begin, please check the list of existing issues to avoid submitting a duplicate issue.

To help us solve this issue as fast as possible, please fill out the following sections:

## Code examples help us better understand the issue - follow the appropriate codepen for the component by going to https://predix-ui.com, finding the component in question, and clicking on the pencil icon under the demo.
        Once you've created your code example, you can save it under a new url.
        Please note that you should NOT use the same methods for production as the ones used in codepen - these methods are not production ready.

**Comment by avm123** [comment]
Hi,

First of all, I am sorry to ask you here this question again here, I can see similar question at: http://forum.predix.io/questions/18025/is-it-possible-to-have-subitems-on-the-subitems-of.html . You are closed here, but the same thing I can see in above url that we cannot add subitems to subitems in Predix app-nav. Please let me know which one is correct, and if we can add subitems or sub menu to another subitems/sub menu, how can I add ? Please provide me any example of it.

Thanks.

**Comment by randyaskin** [comment]
As Greg said on the forums, you can only have one level of nested items.
