### ISSUE TITLE
Multiple web-animations-next imports breaks px-app-nav

### ISSUE THREAD

**Issue by nonmetalhail** [PredixDev/px-app-nav#35]
Related to this issue on [timeseries](https://github.com/PredixDev/px-vis-timeseries/issues/44) 

Also related to this open issue on [web animations](https://github.com/web-animations/web-animations-js/issues/88)

## Expected behavior and actual behavior:

Multiple imports of web-animations-next breaks animations in px-app-nav. This includes other components which import web-animations-next and/or use neon-animation components.

## Steps to reproduce the problem:
Add `<script src="../../web-animations-js/web-animations-next.min.js"></script>` to any site importing px-app-nav or import another component with the above script tag or import another component using neon-animation.

Also viewable here: [http://codepen.io/anon/pen/wJrJLB?editors=1001](http://codepen.io/anon/pen/wJrJLB?editors=1001)

## Environment (_component version number, Browser (including version), operating system, hardware, etc_):

Presumable All but only tested in Chrome

## Suggested Fix
Upgrade px-app-nav to use neon-animation. Neon-animation does not exhibit these problems.

**Comment by mdwragg** [comment]
Fixed in 435879a

**Comment by gstroup** [comment]
Perfect!  Thanks for the quick fix.

**Comment by mdwragg** [comment]
No worries! Make sure you pull the latest @gstroup, I had to make a further fix last night...

**Comment by gstroup** [comment]
Got version 1.10.9.  Looks good.  Thanks.

**Comment by mdwragg** [comment]
👍
