### ISSUE TITLE
Nav item label height not adjustable

### ISSUE THREAD

**Issue by satishpoul** [PredixDev/px-app-nav#37]
## Expected behavior and actual behavior: 
px-app-nav works well till the nav-item label is with limited characters. As the character length increases nav-item height is not adjustable. Refer screenshot below.

## Screenshot :
![px-app-nav](https://cloud.githubusercontent.com/assets/3095213/24648317/ea603a06-1940-11e7-8859-1977673ec36c.jpg)

**Comment by davidrleonard** [comment]
This issue is for an outdated version of px-app-nav (v1.x). The new version (v2.x+) has a revamped API and attempts to truncate overly long nav items. Please upgrade to get this new functionality.
