### ISSUE TITLE
Custom CSS Variable Declarations Without Default Value

### ISSUE THREAD

**Issue by gedesigntech** [PredixDev/px-app-nav#39]
# Submit an Issue

Hi,

Thanks for helping us improve the Predix UI platform by submitting an issue.

Before you begin, please check the list of existing issues to avoid submitting a duplicate issue.

To help us solve this issue as fast as possible, please fill out the following sections:

## Expected behavior and actual behavior:

There are multiple lines in **px-app-nav-predix.scss** where there are custom CSS variable declarations without default value.  For example, see Line 25.

Expected:
  background-color: var(--px-app-nav-background-color, [some default value]); //$gray-darkest;

Actual:
  background-color: var(--px-app-nav-background-color); //$gray-darkest;

When the SASS files are compiled, these default-less custom variables are carried over to the '*-styles.html' file, when these variables will resolve to values inherited from the parent.

I'm not sure if this will produce undesired results, but the Styling docs (see Screenshot) otherwise mention of default values.  It seems having default values is also best practice.

## Steps to reproduce the problem:

n/a

## Environment (_component version number, Browser (including version), operating system, hardware, etc_):

n/a

## Screenshots:

This screenshot for **px-app-nav**'s Styling info in predix-ui.com shows default values, but I'm unable to find how these defaults are declared in the SCSS files.

![screen shot 2017-04-13 at 4 37 27 pm](https://cloud.githubusercontent.com/assets/15674937/25028248/cce8c212-2067-11e7-858b-9975efe3c9c6.png)

## Code examples help us better understand the issue - follow the appropriate codepen for the component by going to https://predix-ui.com, finding the component in question, and clicking on the pencil icon under the demo.
        Once you've created your code example, you can save it under a new url.
        Please note that you should NOT use the same methods for production as the ones used in codepen - these methods are not production ready.

**Comment by randyaskin** [comment]
These are defined in px-theme. We are actually talking about moving *all* of our components to this model, so that if neither px-theme nor px-dark-theme (nor any arbitrary theme) is used, a non-styled version of the component would be served. This somewhat follows the Google model of separating behavior (iron-*) from theming or style (paper-*). If teams don't want to use Polymer / style modules at all, the CSS vars can always be defined in a custom-style block at the document level of the application. Feel free to stop over and chat with Martin if you have further questions.

**Comment by gedesigntech** [comment]
I just looked again in px-app-nav.html and see no reference in px-theme.html .  It's quite reasonable to expect that customers adopt a theme; and if they don't, then they take care of it themselves.  I support that strategy.  It's just that the code in the repo and the Styling info in predix-ui.com are not in sync, and can cause confusion.

**Comment by randyaskin** [comment]
Good point, I've removed the default values from the docs. We'll continue doing so as we remove the defaults from the sass in each component during the redesign.

We know we need to improve the quality/availability of documentation on theming in general. There's some on predix.io, but it's on our list of improvements to cross-post the content or link to it from predix-ui.com.
