### ISSUE TITLE
Double click on hamburger brings a mess

### ISSUE THREAD

**Issue by qrwacek** [PredixDev/px-app-nav#41]
## Expected behavior and actual behavior:
Component is collapsed and menu items text is visible under icons (check screenshot below) after double click on hamburger. Component should be expanded and menu items text should be placed on the right of the icons

## Steps to reproduce the problem:
Double click on hamburger when nav is expanded. This also occurs on https://www.predix-ui.com/#/components/px-app-nav/

## Environment
Chrome Version 58.0.3029.81
Windows 7
DELL laptop

## Screenshots:
![px-app-nav-bug](https://cloud.githubusercontent.com/assets/1021755/25483627/e6b6d54a-2b56-11e7-9702-ace32b0e9608.png)

**Comment by randyaskin** [comment]
Fixed in v1.10.11. Thanks!
