### ISSUE TITLE
Long label name issue

### ISSUE THREAD

**Issue by Dhawal0693** [PredixDev/px-app-nav#42]
I am facing an issue for the labels which has big names i.e the label doen't fit into the ap-nav frame and it splits into two rows.

for eg:  'Centrifugal Compressor Opt' is the name of one of my app and in app-nav it splits into 'Centrifugal Compressor' as one row and 'Opt' in another row. Due to this there is issue in the sub-items for it.
Issue is clearly mentioned and explained in the docx.
By seeing the document you would be able to understand  properly.

[px-app-nav issue.docx](https://github.com/PredixDev/px-app-nav/files/1000439/px-app-nav.issue.docx)

**Comment by davidrleonard** [comment]
This issue is for an outdated version of px-app-nav (v1.x). The new version (v2.x+) has a revamped API and attempts to truncate overly long nav items. Please upgrade to get this new functionality.
