### ISSUE TITLE
--px-app-nav-hamburger-button-color not getting changed

### ISSUE THREAD

**Issue by ManjuKumar** [PredixDev/px-app-nav#44]
Hi,

I observed that --px-app-nav-hamburger-button-color custom properties for styling is not able to change the color of the hamburger button.

Thanks

**Comment by randyaskin** [comment]
That would be because someone hardcoded it in the HTML... 
Fixed in v1.10.13 (make sure you don't grab the 2.0.0-prerelease yet).
