### ISSUE TITLE
all Nav items remains selected when using in vulcanized html file

### ISSUE THREAD

**Issue by nehak123** [PredixDev/px-app-nav#45]
# Submit an Issue

Hi,

Thanks for helping us improve the Predix UI platform by submitting an issue.

Before you begin, please check the list of existing issues to avoid submitting a duplicate issue.

To help us solve this issue as fast as possible, please fill out the following sections:

## Expected behavior and actual behavior:
[px-nav issue.docx](https://github.com/PredixDev/px-app-nav/files/1079981/px-nav.issue.docx)
Actual behavior : all Nav items remains selected state and not able to see sub-items if any, when we are trying to run vulcanized file(where we are using px-app-nav as element) using gulp command .

## Steps to reproduce the problem:
we are running  "gulp serve:dist:start" command.

## Environment (_component version number, Browser (including version), operating system, hardware, etc_):
px-app-nav component version : 1.10.12
## Code examples help us better understand the issue - follow the appropriate codepen for the component by going to https://predix-ui.com, finding the component in question, and clicking on the pencil icon under the demo.
        Once you've created your code example, you can save it under a new url.
        Please note that you should NOT use the same methods for production as the ones used in codepen - these methods are not production ready.

**Comment by davidrleonard** [comment]
Hi @nehak123, thanks for submitting a bug report.

Could you please take the text/images out of the .docx and paste them inline into your Github Issue? This helps us more easily address questions/problems, and ensures that people reading this issue in the future will be able to understand the reported problem and possibly use the fix in their own app.

Thanks.

**Comment by davidrleonard** [comment]
This issue is for an outdated version of px-app-nav (v1.x). The new version (v2.x+) has a revamped API and should no longer exhibit this issue. Please upgrade to get the fix.
