### ISSUE TITLE
Horizontal Nav should be fixed at the top of the page:

### ISSUE THREAD

**Issue by ppeyro** [PredixDev/px-app-nav#50]
## Expected behavior and actual behavior:

By default, horizontal Nav should be locked to the top of the page, so when scrolling the page content will scroll below it.

## Environment:

App-nav: Master/Latest Pull today
Browser: Chrome

## Screenshots:

![screen shot 2017-07-18 at 2 01 33 pm](https://user-images.githubusercontent.com/10835611/28339756-06d8be3c-6bc2-11e7-8539-14efb472e4e4.png)

/cc @davidrleonard

**Comment by davidrleonard** [comment]
In horizontal/collapsed mode, the developer needs to set the nav to `position:absolute` or `position:fixed` and decide how it will stick to the top of the page. Or they need to use px-app-helpers' nice navbar wrapper. Moving this to #70 so we can document.
