### ISSUE TITLE
In collapsed View: Truncation of long labels can cause removal of the sub-nav down-arrow.

### ISSUE THREAD

**Issue by ppeyro** [PredixDev/px-app-nav#58]
## Behavior:

With nav item labels that are longer and have a sub-nav in the collapsed view, the down arrow for the sub-nav gets clipped off leaving no indication that there is a subnav.

Attaching a screenshot of design spec with the code implementation.

## Environment:
App-Nav: Master-7/18 evening Pull
Browsers: Chrome & Safari9

## Screenshot:

<img width="999" alt="screen shot 2017-07-19 at 12 50 44 pm" src="https://user-images.githubusercontent.com/10835611/28386608-f295e8c2-6c80-11e7-81f1-c35afd6a3cc6.png">

**Comment by davidrleonard** [comment]
@ppeyro and I determined this was not an issue.
