### ISSUE TITLE
Menu item is not highlighted correct after clicking back

### ISSUE THREAD

**Issue by clementchi** [PredixDev/px-app-nav#6]
When navigate to previous history using back button the previous menu is not highlighted. The active menu item and url are out of sync. 

It seems working after adding popstate event listener. 

      var self = this;
      window.addEventListener('popstate', function(event) {
        self.markSelected(window.location.href);
      });

**Comment by ek** [comment]
Nice catch, thanks Clement!

This issue is now resolved on master with version v1.0.10
