### ISSUE TITLE
Firefox:  Errors in console log on font download failures.

### ISSUE THREAD

**Issue by ppeyro** [PredixDev/px-app-nav#60]
Noticed multiple errors in **Firefox** console log only when loading the collapsed view of app-nav:

Initially the text wouldn't render at all, but eventually it renders fine, but the errors are still present.

## Environment 

App-Nav: Master-7/18 evening Pull
Browsers: Chrome & Safari9:

## Screenshot:

![screen shot 2017-07-19 at 3 10 45 pm](https://user-images.githubusercontent.com/10835611/28391857-7976df32-6c94-11e7-9ce6-155a36650d04.png)

**Comment by davidrleonard** [comment]
Closing this here for now. If we see this in another repo we will need to investigate at the px-theme level.
