### ISSUE TITLE
Mobile: Sub-nav items not visible when rotating between portrait/landscape mode.

### ISSUE THREAD

**Issue by ppeyro** [PredixDev/px-app-nav#62]
## Behavior:

Edge case:  If the last item in the nav has a sub-nav, when rotating from portrait to landscape mode and sometimes vice versa, the last sub-nav item is not visible and you cannot swipe to view it either.

## Environment :

App-Nav: Master-7/18 evening Pull
Browsers: Safari/ios10.3.1 +iphone6 Plus

## Screenshot:

<img width="1415" alt="screen shot 2017-07-19 at 4 17 47 pm" src="https://user-images.githubusercontent.com/10835611/28393930-a6cd911a-6c9e-11e7-945c-0d6598389444.png">

/cc @davidrleonard

**Comment by davidrleonard** [comment]
@ppeyro Make sure you aren't trying to scroll up from the very bottom of the screen (that is a native behavior in iOS that opens the bottom drawer). If you scroll up on the dropdown from the middle of the screen it should scroll to show the missing item.
