### ISSUE TITLE
Mobile: Vertical nav clipped at the bottom in portrait mode.

### ISSUE THREAD

**Issue by ppeyro** [PredixDev/px-app-nav#63]
## Behavior:

Vertical nav clipped at the bottom in portrait mode, leaving some of the nav options unselectable.

## Environment:

App-Nav: Master-7/18 evening Pull
Browsers: Safari/ios10.3.1 +iphone6 Plus

## Screenshot:

<img width="1424" alt="screen shot 2017-07-19 at 5 31 26 pm" src="https://user-images.githubusercontent.com/10835611/28395393-8b4b52f6-6ca8-11e7-9875-43daa5558f34.png">

/cc @davidrleonard

**Comment by davidrleonard** [comment]
The vertical nav cannot be used on mobile devices. The developer must switch to the collapsed nav (there's no hover concept in touch devices, so no way to show it.) Adding to the catch-all docs issue #70 to make this is documented.
