### ISSUE TITLE
Remove statics from api docs

### ISSUE THREAD

**Issue by ppeyro** [PredixDev/px-app-nav#65]
## Expected behavior and actual behavior:

Not sure if statics belongs in property section of api docs.
Should be removed?

## Environment:

App-Nav: Master-7/18 evening Pull
Browsers: Chrome

## Screenshot:

![screen shot 2017-07-20 at 2 31 47 pm](https://user-images.githubusercontent.com/10835611/28439849-927550d0-6d58-11e7-8d35-b3391eb16e35.png)

/cc @davidrleonard

**Comment by davidrleonard** [comment]
Fixed in a6dee2e307db3d011a9414ae29e51adf765443f2 (v2.0.1)
