### ISSUE TITLE
Change references from "subitem" to "children"

### ISSUE THREAD

**Issue by ppeyro** [PredixDev/px-app-nav#66]
For consistency, we should change all references from "subitem" to "children".
Here's the list so far:
1. API doc (3 instances in items property)
2. Demo code (but the demo should be redone anyway, will open a new issue for that).
3. px-app-nav-group.html: (5 references in comment sections).
4. px-app-nav-item.es6.js: (2 references, 1 in comment, one actual property)
5. px-app-nav-subgroup.html: ( 2 comments)
6. px-app-nav-subitem.es6.js: ( (2 references, 1 in comment, one in code)
7. px-app-nav.es6.js: (3 comments)
8. px-app-nav.html:(17 instances, all over the code).

## Environment:
App-Nav: Master-7/18 evening Pull
Browsers: Chrome

## Screenshots :
![screen shot 2017-07-20 at 3 24 34 pm](https://user-images.githubusercontent.com/10835611/28441845-c4d6dbc6-6d61-11e7-838d-db3d696cf971.png)

![screen shot 2017-07-20 at 3 39 52 pm](https://user-images.githubusercontent.com/10835611/28441855-d0e00eba-6d61-11e7-9e6f-a6359421999d.png)

/cc @davidrleonard

**Comment by davidrleonard** [comment]
Fixed in a6dee2e307db3d011a9414ae29e51adf765443f2 (v2.0.1)
