### ISSUE TITLE
Demo should be updated.

### ISSUE THREAD

**Issue by ppeyro** [PredixDev/px-app-nav#67]
We should update the demo to show more complex nav implementations if possible.
The current one looks pretty sad ... :)

## Environment:

App-Nav: Master-7/18 evening Pull
Browsers: Chrome

## Screenshot:

![screen shot 2017-07-20 at 3 44 14 pm](https://user-images.githubusercontent.com/10835611/28441937-508c0254-6d62-11e7-89ac-519a800589f9.png)

/cc @davidrleonard

**Comment by davidrleonard** [comment]
Moved to catch-all demo/docs issue #70.
