### ISSUE TITLE
px-app-nav does not work in IE11 & Edge

### ISSUE THREAD

**Issue by bharat-srinivasan** [PredixDev/px-app-nav#75]
## Expected behavior and actual behavior:
px-app-nav component demo does not load when opened in IE Edge.

## Steps to reproduce the problem:
1. Open https://www.predix-ui.com in IE Edge browser.
2. Navigation to px-app-nav component.
3. The spinner keeps running indefinitely.
4. Open the developer tools to see errors.

## Environment
- OS: Windows 10
- Browser: Edge 13.x and IE 11

## Screenshots
![screen shot 2017-08-17 at 10 50 09](https://user-images.githubusercontent.com/15170423/29397271-af4cc100-833a-11e7-8830-57d6141c3d61.png)

## Code Pen
https://codepen.io/bharat-srinivasan/pen/ZXvdXG

**Comment by mdwragg** [comment]
This is likely a transpilation issue. To verify please try the following:

```
git clone https://github.com/PredixDev/px-app-nav
cd px-app-nav
npm install
bower install
npm install -g polymer-cli
polymer serve
```
(browse to http://127.0.0.1:8000/components/px-app-nav/)

We support the last two versions of evergreen browsers as detailed here: https://www.predix-ui.com/#/about/introduction
