### ISSUE TITLE
this.$.groupcontainer undefined bug when setting animationConfig in properties

### ISSUE THREAD

**Issue by gotoashishgupta** [PredixDev/px-app-nav#77]
Hi,

Thanks for helping us improve the Predix UI platform by submitting an issue.

Before you begin, please check the list of existing issues to avoid submitting a duplicate issue.

To help us solve this issue as fast as possible, please fill out the following sections:

## Expected behavior and actual behavior:
When using the component in angular application, Upon clicking on menu items with submenu following error is coming:
this.$.groupcontainer undefined
bug when setting animationConfig in properties

## Steps to reproduce the problem:
Use the component with submenu items in an angular app

## Environment (_component version number, Browser (including version), operating system, hardware, etc_):
v2.0.8

## Screenshots (_optional, but very helpful_):
<img width="1399" alt="screen shot 2017-09-19 at 2 03 55 pm" src="https://user-images.githubusercontent.com/1331478/30584730-41f8abbe-9d48-11e7-8b94-a0a52deafedb.png">
<img width="1391" alt="screen shot 2017-09-19 at 2 04 21 pm" src="https://user-images.githubusercontent.com/1331478/30584735-481b51a4-9d48-11e7-8360-3b48a3a2a065.png">

## Code examples help us better understand the issue - follow the appropriate codepen for the component by going to https://predix-ui.com, finding the component in question, and clicking on the pencil icon under the demo.
 1. define animationConfig in ready callback

SOLUTION:
Refer: https://github.com/PolymerElements/neon-animation/issues/226
solution: https://github.build.ge.com/212591749/px-app-nav/tree/v2.0.9-alpha.0.1

<img width="1179" alt="screen shot 2017-09-19 at 2 07 53 pm" src="https://user-images.githubusercontent.com/1331478/30584766-5dee4af4-9d48-11e7-9728-e6c6281aeb49.png">

**Comment by davidrleonard** [comment]
Fixed in 26d93f230cbd0eea1fc9595c8f933aa8dceaec56. Please update your dependency on px-app-nav to v2.1.1 or later to get this fix.
