### ISSUE TITLE
Support Polymer 2.0.

### ISSUE THREAD

**Issue by shinxi** [PredixDev/px-app-nav#80]
Same as https://github.com/PredixDev/px-progress-bar/issues/6, not sure if there is a plan to upgrade to polymer 2.0. @davidrleonard 

## Expected behavior and actual behavior:
Expected behavior: px-app-nav works as expected with polymer 2.0
Actual behavior: px-app-nav doesn't work with polymer 2.0

## Steps to reproduce the problem:
https://codepen.io/anon/pen/zEQvaV?&editors=1001

## Environment (_component version number, Browser (including version), operating system, hardware, etc_):
px-app-nav: 2.0.11
polymer: 2.0.0
Browser: Google Chrome 61.0.3163.100
operating system: macOS Sierra 10.12.6

## Screenshots (_optional, but very helpful_):
![image](https://user-images.githubusercontent.com/1262296/31885846-8b6c2e4a-b7b7-11e7-8e64-e17c9e2619f7.png)

## Code examples
https://codepen.io/anon/pen/zEQvaV?&editors=1001

**Comment by mdwragg** [comment]
As per the bower dependencies in this component, it does not support Polymer 2.x at the moment.

We’re working on Polymer 2 support this quarter.
