### ISSUE TITLE
Open up px-app-nav to use any icons rather than just px-icon-set

### ISSUE THREAD

**Issue by sjw787** [PredixDev/px-app-nav#83]
This is a feature request for the ability to use external icon sets like font-awesome icons in the px-app-nav.

Currently, the supported icon set is pretty limited in its selection. This doesn't make the app nav very useable.

**Comment by skistz** [comment]
We'd prefer to extend the px-icon-set as icons are needed to remain consistent with the design language. Design guidelines for new icons can be found on https://www.predix-ui.com/#/design/iconography. The design system team is happy to work with you on extending the set.

**Comment by stephaniebrenton** [comment]
@skistz @sjw787 I'm the Senior Staff UX Designer on the project. Let's set up some time to chat early next week. This is going to be an issue we will encounter regularly, having adopted the old px standards in our live application. We need to be able to move over to new PX gradually.

**Comment by davidrleonard** [comment]
Thanks for weighing in @skistz. Hope you all connect about this.

From a technical standpoint, px-app-nav supports using any icons defined through iron-iconset-svg and loaded on the page.

Relevant links:
* https://www.predix-ui.com/#/develop/icons (see "Using non-px icons")
* https://github.com/PredixDev/px-icon-set/blob/master/examples/use-iron-icon.html (Example of mixing/matching px-icon-set icons and Google's default iron-icons)
* https://www.webcomponents.org/element/PolymerElements/iron-iconset-svg
