### ISSUE TITLE
Selected nav-item style issue with Angular routing guards

### ISSUE THREAD

**Issue by dilipchandima** [PredixDev/px-app-nav#84]
I'm using `px-app-nav` with Angular and use https://angular.io/api/router/CanActivate, https://angular.io/api/router/CanDeactivate like router guards to guard the routing with some unsaved changes ( dirty application status ).

**When click on `px-app-nav` item it shows like selected ( CSS changed ) but in that time If application is dirty the route change will not happen but the selected nav item is not change to user existing route url.**

## Suggestion

If this selection can be done by checking the URL change in t.he browser this problem can be prevent.

**Comment by davidrleonard** [comment]
This is not the model that px-app-nav uses. Relying on the URL for setting selected nav item state would force app developers to use px-app-nav in that way only, and not allow different routing schemes. If you want to implement this yourself you could listen to the selected-changed event and reset the selected item to the last selected item, then update px-app-nav when your URL changes.
