### ISSUE TITLE
How to add px-login item in the bottom of vertical App Nav

### ISSUE THREAD

**Issue by benjaminliugang** [PredixDev/px-app-nav#85]
Not sure if it already supports this kind of feature, I tried with https://codepen.io/randyaskin/pen/MmpgEm?editors=1100 in https://github.com/PredixDev/px-app-nav/issues/40, but it does not work. Does it have any other sample of it or it does not support, we need to wrap it by ourselves?

`"px-app-nav": "^2.0.11"`

 
![image](https://user-images.githubusercontent.com/1411188/34162331-46d8363c-e50e-11e7-89b6-87a2b79d2acd.png)

![image](https://user-images.githubusercontent.com/1411188/34162339-4f4d2796-e50e-11e7-8519-6e78d1488117.png)

**Comment by randyaskin** [comment]
You can use `slot="actions"` to add something to the right of a horizontal nav or the bottom of a vertical nav. However the px-login component is not currently stateful / doesn't listen to the expand/collapse notifications of px-app-nav to change itself from expanded to collapsed, I was just looking into this yesterday. I'll let you know what I find out.

**Comment by benjaminliugang** [comment]
@randyaskin , Thanks a lot for your quick reply! I tried with `slot`, it works. But I found some other issues:

- Expand and collapse not work(as you mentioned)
- The slot part shows after the last item, not stand in the bottom of the nav. I checked the code, found the slot section class `app-nav__actions` does not include any style.
`      <section class="app-nav__actions" id="actions">
        <slot id="actionsvisible" name="actions"></slot>
      </section>`
- When the nav collapsed, the login component still shows the user name

![image](https://user-images.githubusercontent.com/1411188/34208250-a9003a16-e5c8-11e7-90f9-596f288ac89a.png)

**Comment by randyaskin** [comment]
I've added the two different states to px-login. I'd like David to take a look at this PR to make sure everything looks correct before we merge it in, but you can refer to the examples and see if it works with your application if you'd like - https://github.com/PredixDev/px-app-nav/pull/86

**Comment by benjaminliugang** [comment]
To be honest, I do not use the px-login(it does not match our requirement) in my application, we created a new one in the bottom of navigation. I tried with your fix, the bottom issue should be resolved. 
And I found you add `collapsed="{{!verticalOpened}}"` in your fix, but I cannot find `collapsed` property in `px-login` component, anything I missed?

**Comment by randyaskin** [comment]
It's here in the latest version: https://github.com/PredixDev/px-login/blob/master/px-login.html#L231-L241

**Comment by benjaminliugang** [comment]
Seems I referred to the wrong version. Thanks!
